//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IT_Forum
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comments
    {
        public int CommentID { get; set; }
        public int ArticleID { get; set; }
        public int UserID { get; set; }
        public string Content { get; set; }
        public System.DateTime Date { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Articles Articles { get; set; }
        public virtual Users Users { get; set; }
    }
}
