//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IT_Forum
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ITForumDBEntities : DbContext
    {
        private static ITForumDBEntities _instance;

        public static ITForumDBEntities GetInst()
        {
            if (_instance == null)
                _instance = new ITForumDBEntities();
            return _instance;
        }

        public ITForumDBEntities()
            : base("name=ITForumDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Articles> Articles { get; set; }
        public virtual DbSet<ArticleStatuses> ArticleStatuses { get; set; }
        public virtual DbSet<Comments> Comments { get; set; }
        public virtual DbSet<Partners> Partners { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
